apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://example-k8s-api.example.com
  name: example-cluster
contexts:
- context:
    cluster: example-cluster
    user: example-user
  name: example-context
current-context: example-context
kind: Config
preferences: {}
users:
- name: example-user
  user:
    # This is a sample kubeconfig file - replace with your actual Kubernetes credentials
    # The certificate data has been removed for security purposes
    client-certificate-data: REDACTED
    client-key-data: REDACTED
